### ISSUE TITLE
Is this working on non deck distros? 

### ISSUE THREAD

**Issue by sounddrill31** [BunnyStrike/deck_revealed#4]
I want to make a "Saul Goodman OS", and I want to use this tool with cubic if it works

**Comment by th3brink** [comment]
Sorry for the late reply. Been working on a full app for the Steam Deck and other OSes. This script is not designed to work on other OSes. I built it quickly to work with the way SteamOS folders are set up. Keep an eye out for the deck revealed app project that is in alpha.

**Comment by sounddrill31** [comment]
Thanks a lot for the reply! 

Realized this early on, and resorted to using plymouth.
